language: generic
os:
  - linux
node_js:
  - node
go:
  - tip
cache: npm
before_script:
  - nvm install node
script:
  - cd frontend
  - npm install
  - npm run build
  - cd ../backend
  - go build -o ../frontend/dist/backend_compiled -i .
  - cd ../frontend
  - npm run deploy