language: generic
os:
  - linux
node_js:
  - node
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
cache: npm
before_script:
  - nvm install node
script:
  - cd frontend
  - npm install
  - npm run build
  - cd ../backend
  - go build -o ../frontend/dist/backend_compiled -i .
  - cd ../frontend
  - npm run deploy