language: generic
os:
  - linux
node_js:
  - node
cache: npm
before_script:
  - nvm install node
script:
  - cd frontend
  - npm install
  - npm run build
  - mv ../backend/ .
  - npm run deploy
notifications:
  email: false