language: generic
node_js:
  - node
cache: npm
before_script:
  - nvm install node
  - gimme --force 1.14.2
script:
  - cd frontend
  - npm install
  - npm run build
  - cd ../backend
  - go build -o ../frontend/dist/backend_compiled
  - cd ../frontend
  - npm run deploy